### ISSUE TITLE
Issue tests for string_of_temp

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#14]
let t8a = string_of_temp (C 2.3) = "2.3C"
let t8b = string_of_temp (F 2.3) = "2.3F"
let t8c = string_of_temp (F (to_f (C 0.0))) = "32.F" ( Is it like this or you want it like this 32.0F)
let t8d = string_of_temp (F (to_f (C 1.0))) = "33.8F"
@Skiadas

**Comment by skiadas** [comment]
Use the float in whatever way OCAML gives it to you.

**Comment by vanh17** [comment]
Okay, I got it, as I expected Thank you Dr. SKiadas

**Comment by vanh17** [comment]
Now all tests passed!
