### ISSUE TITLE
try_thunk implementation-Assignment4

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#26]
cannot use the right type...............
All have exn option instead of 'a option.

**Comment by vanh17** [comment]
let try_thunk f = try (f ()) with 
                  | Failure e -> None
                  | v -> Some v
I have this code, but however, it was type (unit->exn option)->exn option instead of 'a option
@Skiadas

**Comment by skiadas** [comment]
v here is an exception, so "Some v" is of type "exception option". The "normal" value of the call f () will naturally be returned from the try-with line, you do not need to "catch it" (but you probably do need to change the expression in your try a bit). You only catch the various kinds of exceptions that you want to handle, not the normal behavior of the expression nor the exceptions you don't care to handle (in this case though I think you are supposed to catch all expressions).

If you didn't have to do any exception stuff (say f could not thrown an exception), how would you write your expression? That's what should go inbetween the "try" and the "with".

**Comment by vanh17** [comment]
Hahahahahahahha,
I got it
let try_thunk f = try (match f () with v -> Some v) with Failure e -> None.
Thank you Dr.@Skiadas

**Comment by vanh17** [comment]
typecheck passed!.

**Comment by skiadas** [comment]
You can simplify it a bit, but you got the idea.

**Comment by vanh17** [comment]
yeah, I think you are right. it just need this 
let try_thunk f = try (Some (f ())) with Failure e -> None
@Skiadas
