### ISSUE TITLE
Issue2 Assignment 3: Is check equivalent to shape * shape?

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#4]
It does recognize shape \* shape,
How come it does not turn the type of shape \* shape into check
It looks like check = shape \* shape, but shape \* shape may no equal to check, is it a subset of sth?
@Skiadas

**Comment by skiadas** [comment]
You should choose more appropriate titles for your issues that describe what the issue is.

check should be equivalent to shape \* shape in all instances.

**Comment by vanh17** [comment]
So if the function return type is check -> some type, it is okay if we have shape \* shape -> some type instead of check -> some type?
@skiadas

**Comment by skiadas** [comment]
You should not be specifying it that way when you define the types of the functions. But it might show up that way when it prints the type back at you. "check" is the name you have given to the type "shape \* shape" to remind you of its purpose. But OCAML doesn't care.

**Comment by vanh17** [comment]
Okay, cool. Thank you so much Dr. @skiadas Skiadas. I actually read the instruction for assignment 3 this time :dancer:

**Comment by skiadas** [comment]
I hope you also read the corresponding notes on type aliases and type variants.

**Comment by vanh17** [comment]
Sure, I have to read them all. Great stuff needs to be taken care of seriously sir

**Comment by vanh17** [comment]
Then, I think this issue is solved :+1:  Thank you Dr. Skiadas

**Comment by skiadas** [comment]
Btw you can close an issue with a comment.
