### ISSUE TITLE
simplify tests-Assignment5

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#83]
Original tests passed!

**Comment by vanh17** [comment]
Dear @Skiadas,
The implementation passed type checked and passed all the original tests. Now where the super fun parts begin. Adding more testssss!

**Comment by vanh17** [comment]
Dear Dr. @Skiadas,
So here is the thing. Mul (Var, Mul (Int 2, Int 6)) does it will return Mul (Int 12, Var) or Mul (Mul (Int 2, Var), Int 6)
My choice is the first one.

**Comment by skiadas** [comment]
Of course, the first one. That gets controlled by the order in which you put the various options.

Btw, you should always write your tests _before_ you write the corresponding code that needs to pass them.

**Comment by vanh17** [comment]
yeah, I am now writing tests, I just leave the code alone this moment, After I have decent amount of tests, at least 30 this time. Then I stopped and look at the code.

**Comment by vanh17** [comment]
Dear Dr. @skiadas 
Do you have any crazy tests for the simplify function. I have implemented 30 tests and run them as a whole. It is now all passed!
Warmest,
P/s: I also check all the tests three times based on your description and it looks right to mee.
Thank you!
