### ISSUE TITLE
const implementation-Assignment6

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#86]
Implement const

**Comment by vanh17** [comment]
Dear Dr. @Skiadas
I have this implementation: let const a = fun f () -> (a, f)
however, it has type 'a->'b->unit->'a*'b

**Comment by skiadas** [comment]
What did you expect it to have? If you trace the requirements you have put in place, that's what you'd be getting I think.

**Comment by vanh17** [comment]
okay, I got it:
It should have 'a->'a stream.
So it has to be recursive like this:
let rec const a = St (fun () -> (a, const a))
typecheck passed!
@skiadas
