### ISSUE TITLE
Issue tests for valid_game

### ISSUE THREAD

**Issue by vanh17** [vanh17/ProgLangAssignments#9]
One play and win
let t4a = valid_game [(Rock, Scissors)] = true
Tie and win
let t4b = valid_game [(Rock, Rock); (Rock, Scissors)] = true
Win, but keep going
let t4c = valid_game [(Rock, Scissors); (Paper, Rock); (Rock, Rock)] = false
No game should be valid
let t4d = valid_game [] = true
Just only ties
let t4e = valid_game [(Rock, Rock); (Scissors, Scissors)] = false

**Comment by vanh17** [comment]
All passed except No game

**Comment by vanh17** [comment]
Dear Dr. @Skiadas, I think that empty game should be true, is it?

**Comment by vanh17** [comment]
Change code, all tests passed!

**Comment by vanh17** [comment]
Dear Dr. @Skiadas,
How can we play an No game? I think we want to treat an No game (empty case) a valid game isn't it?

**Comment by skiadas** [comment]
You mean if the game is an empty list? That should be a valid game, and a tie.

**Comment by vanh17** [comment]
yup, as I expected :) Now all set. Thank you so much Dr. @Skiadas. 
Btw: I did listen to your advice and add more tests along with opened and closed corresponding issues
